### ISSUE TITLE
Please deploy a new version to include a243d01c508e67/added missing set_line_width calls in HTML5 canvas backend

### ISSUE THREAD

**Issue by redforks** [plotters-rs/plotters-canvas#11]
This commit is very important, because it fixes many line width problems.

**Comment by vpochapuis** [comment]
> This commit is very important, because it fixes many line width problems.

Hello!
Indeed this issue is still present on the currently released version `0.3.0`.
![image](https://github.com/plotters-rs/plotters-canvas/assets/75721408/f8bb305f-5fa2-4b51-90f9-3cbb1868bc65)

While the main branch has some nice commits and a version of `0.3.1`.

Until this is released, for those that want to take advantage of the commits on main,
you can add a `patch` to your `Cargo.toml` file like so:
```toml
[patch.crates-io]
plotters-canvas = { git = "https://github.com/plotters-rs/plotters-canvas.git", branch = "main" }
```
Its also possible to use `rev` instead of `branch` in order to target a specific commit.
